### PR TITLE
Update Gradle wrapper and improve README

### PR DESCRIPTION
**Pull request by guilgaly**
- Update Gradle wrapper since we support the latest version
- Link to the javadoc for the Java API rather than Scala
- Add basic info + doc links for Gatling Enterprise, since we'll link directly to the samples from the Enterprise apps

### CODE REVIEW

**Comment by guilgaly** [comment]
Question: is this a good README model to adapt for all the other sample projects?

**Review by slandelle — APPROVED** [review]

**Comment by slandelle** [comment]
> Question: is this a good README model to adapt for all the other sample projects?

Yes. Could you please do the same for the other ones?

**Comment by guilgaly** [comment]
I've updated a couple things, and also added a commit to switch from Asciidoc to Markdown, since that's what we use everywhere else. I'll open pull requests for all the other demo projects too.

**Comment by slandelle** [comment]
Thanks!

**Pull request merged**
